# Generated by Django 3.2.3 on 2021-05-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='mesaure_unit',
        ),
        migrations.AlterField(
            model_name='buy',
            name='buy_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
