# Generated by Django 3.2.3 on 2021-05-28 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0002_auto_20210527_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buy_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 11, 40, 40, 391427)),
        ),
    ]
