# Generated by Django 3.2.3 on 2021-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0004_alter_buy_buy_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
